# Generated by Django 5.0.1 on 2024-05-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_pricerange_bike_is_placed_order_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='Cart_object',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='Bike_object',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
